
package Ventanas;

import java.awt.Dimension;
import javax.swing.JDesktopPane;



/**
 *
 * @author leona
 */
public class FrmMenu extends javax.swing.JFrame {

    public JDesktopPane jDesktopPane_Menu;
            
    
    public FrmMenu() {
        initComponents();
        
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("El Horno Feliz");
        
        this.setLayout(null);
        jDesktopPane_Menu = new JDesktopPane(); 
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
        
        this.jDesktopPane_Menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_Menu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_nuevo_usuario = new javax.swing.JMenuItem();
        jMenuItem_gestionar_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem_gestionar_producto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_venta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_rep_dia = new javax.swing.JMenuItem();
        jMenuItem_rep_sem = new javax.swing.JMenuItem();
        jMenuItem_rep_men = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_recetas = new javax.swing.JMenuItem();
        jMenuItem_Insumos = new javax.swing.JMenuItem();
        jMenu_log_out = new javax.swing.JMenu();
        jMenuItem_log_out = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevousu.png"))); // NOI18N
        jMenuItem_nuevo_usuario.setText("Nuevo Usuario");
        jMenuItem_nuevo_usuario.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_nuevo_usuario);

        jMenuItem_gestionar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestusu.png"))); // NOI18N
        jMenuItem_gestionar_usuario.setText("Gestionar Usuarios");
        jMenuItem_gestionar_usuario.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_gestionar_usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuepro.png"))); // NOI18N
        jMenuItem_nuevo_producto.setText("Nuevo Producto");
        jMenuItem_nuevo_producto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nuevo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_nuevo_producto);

        jMenuItem_gestionar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestpro.png"))); // NOI18N
        jMenuItem_gestionar_producto.setText("Gestionar Productos");
        jMenuItem_gestionar_producto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_gestionar_producto);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Produccion.png"))); // NOI18N
        jMenuItem1.setText("Ingresar Produccion");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ventas.png"))); // NOI18N
        jMenu3.setText("Ventas");
        jMenu3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        jMenuItem_venta.setText("Iniciar Venta");
        jMenuItem_venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ventaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_venta);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reporte.png"))); // NOI18N
        jMenu4.setText("Reportes");
        jMenu4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_rep_dia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repdia.png"))); // NOI18N
        jMenuItem_rep_dia.setText("Reporte Diario");
        jMenuItem_rep_dia.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_rep_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_rep_diaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_rep_dia);

        jMenuItem_rep_sem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repsem.png"))); // NOI18N
        jMenuItem_rep_sem.setText("Reporte Semanal");
        jMenuItem_rep_sem.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_rep_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_rep_semActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_rep_sem);

        jMenuItem_rep_men.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repmen.png"))); // NOI18N
        jMenuItem_rep_men.setText("Resporte Mensual");
        jMenuItem_rep_men.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_rep_men.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_rep_menActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_rep_men);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Almacen.png"))); // NOI18N
        jMenu6.setText("Almacen ");
        jMenu6.setActionCommand("");
        jMenu6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_recetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recetas.png"))); // NOI18N
        jMenuItem_recetas.setText("Recetas");
        jMenuItem_recetas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_recetasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_recetas);

        jMenuItem_Insumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto1.png"))); // NOI18N
        jMenuItem_Insumos.setText("Insumos");
        jMenuItem_Insumos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_Insumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_InsumosActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_Insumos);

        jMenuBar1.add(jMenu6);

        jMenu_log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CerrarSesion.png"))); // NOI18N
        jMenu_log_out.setText("Cerrar Sesion");
        jMenu_log_out.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenu_log_out.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_out.png"))); // NOI18N
        jMenuItem_log_out.setText("Cerrar Sesion");
        jMenuItem_log_out.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_log_outActionPerformed(evt);
            }
        });
        jMenu_log_out.add(jMenuItem_log_out);

        jMenuBar1.add(jMenu_log_out);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_usuarioActionPerformed
        InternNueUsu internneuusu = new InternNueUsu();
        jDesktopPane_Menu.add(internneuusu);
        internneuusu.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevo_usuarioActionPerformed

    private void jMenuItem_gestionar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_usuarioActionPerformed
        InternGestUsu interngestusu = new InternGestUsu();
        jDesktopPane_Menu.add(interngestusu);
        interngestusu.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionar_usuarioActionPerformed

    private void jMenuItem_nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_productoActionPerformed
        InternNuevPro internnuevpro = new InternNuevPro();
        jDesktopPane_Menu.add(internnuevpro);
        internnuevpro.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevo_productoActionPerformed

    private void jMenuItem_InsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_InsumosActionPerformed
        InternInsumos interninsumos = new InternInsumos();
        jDesktopPane_Menu.add(interninsumos);
        interninsumos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_InsumosActionPerformed

    private void jMenuItem_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ventaActionPerformed
        Vendedor venta = new Vendedor();
        jDesktopPane_Menu.add(venta);
        venta.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ventaActionPerformed

    private void jMenuItem_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_log_outActionPerformed
        Login login = new Login();
        
        // 2. Hacer visible la ventana de Login (como ventana independiente)
        login.setVisible(true);
        
        // 3. Cerrar y liberar los recursos de la ventana actual (el Menú)
        this.dispose();
    }//GEN-LAST:event_jMenuItem_log_outActionPerformed

    private void jMenuItem_rep_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_rep_diaActionPerformed
        InternRepDia internrepdia = new InternRepDia();
        jDesktopPane_Menu.add(internrepdia);
        internrepdia.setVisible(true);
    }//GEN-LAST:event_jMenuItem_rep_diaActionPerformed

    private void jMenuItem_gestionar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_productoActionPerformed
        InternGestPro interngestpro = new InternGestPro();
        jDesktopPane_Menu.add(interngestpro);
        interngestpro.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionar_productoActionPerformed

    private void jMenuItem_rep_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_rep_semActionPerformed
        InternRepSem internrepsem = new InternRepSem();
        jDesktopPane_Menu.add(internrepsem);
        internrepsem.setVisible(true);
    }//GEN-LAST:event_jMenuItem_rep_semActionPerformed

    private void jMenuItem_rep_menActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_rep_menActionPerformed
        InternRepMen internrepmen = new InternRepMen();
        jDesktopPane_Menu.add(internrepmen);
        internrepmen.setVisible(true);
    }//GEN-LAST:event_jMenuItem_rep_menActionPerformed

    private void jMenuItem_recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_recetasActionPerformed
        InternRecetas internrecetas = new InternRecetas();
        jDesktopPane_Menu.add(internrecetas);
        internrecetas.setVisible(true);
    }//GEN-LAST:event_jMenuItem_recetasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        InternIngPro interningpro = new InternIngPro();
        jDesktopPane_Menu.add(interningpro);
        interningpro.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_Insumos;
    private javax.swing.JMenuItem jMenuItem_gestionar_producto;
    private javax.swing.JMenuItem jMenuItem_gestionar_usuario;
    private javax.swing.JMenuItem jMenuItem_log_out;
    private javax.swing.JMenuItem jMenuItem_nuevo_producto;
    private javax.swing.JMenuItem jMenuItem_nuevo_usuario;
    private javax.swing.JMenuItem jMenuItem_recetas;
    private javax.swing.JMenuItem jMenuItem_rep_dia;
    private javax.swing.JMenuItem jMenuItem_rep_men;
    private javax.swing.JMenuItem jMenuItem_rep_sem;
    private javax.swing.JMenuItem jMenuItem_venta;
    private javax.swing.JMenu jMenu_log_out;
    // End of variables declaration//GEN-END:variables
}
