package Ventanas;
import java.sql.*;
import Conexion.Conexion;
import Controlador.ctrl_nuevpro;
import Modelo.NuevoProducto;
import javax.swing.JOptionPane;

/**
 *
 * @author leona
 */
public class InternNuevPro extends javax.swing.JInternalFrame {
   int obteneridproducto = 0;
    // Se recomienda inicializar las variables del controlador y modelo
    // si no se están usando inyección de dependencias.
    
    public InternNuevPro() {
        initComponents();
        this.setSize(400,300);
        this.setTitle("Nuevo Producto");
        
        // Carga los sabores de la BD al ComboBox al iniciar.
        this.cargarComboSabores(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVO PRODUCTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Relleno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, -1));

        txtPrecio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, -1));

        jButtonGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, 30));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Fresa", "Vainilla", "Cajeta", "Crema Pastelera", "Mantequilla", "Piña", "Naranja", "Nuez", "Azucar", "Moka", "Nata", "Miel", "Aniz", "Canela", "N/A" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jLabelFondo.setToolTipText("");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 440, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        NuevoProducto NuePro = new NuevoProducto();
        // Se instancia el controlador para usar su método.
        ctrl_nuevpro ctrl_nuepro = new ctrl_nuevpro();
        String sabor = "";
        
        // 1. Obtener Sabor y validar nulos
        if (jComboBox1.getSelectedItem() != null) {
            sabor = jComboBox1.getSelectedItem().toString().trim();
        } else {
            // Si no hay ítems en el combo, el sabor será nulo
             JOptionPane.showMessageDialog(null, "No hay sabores disponibles, verifique la base de datos.");
             return;
        }
        
        // 2. Validar campos obligatorios
        if (txtNombre.getText().trim().isEmpty() || txtPrecio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete los campos Nombre y Precio.");
            return;
        }
        
        // 3. Validar Producto Existente
        if(ctrl_nuepro.existeProducto(txtNombre.getText().trim())){
            JOptionPane.showMessageDialog(null, "El producto ya existe en la base de datos");
            return;
        }
        
        // 4. Validar Selección de Sabor
        if (sabor.equalsIgnoreCase("Seleccione Sabor:")) {
            JOptionPane.showMessageDialog(null, "Seleccione un sabor válido.");
            return;
        }
        
        // 5. Procesar Precio
        float precio = 0;
        try {
            String PrecioTXT = txtPrecio.getText().trim();
            boolean aux = false;
            
            // Logica para reemplazar la coma por punto para el parseo de Float.
            for(int i = 0; i < PrecioTXT.length(); i++){
                if(PrecioTXT.charAt(i)==','){
                    PrecioTXT = PrecioTXT.replace(",",".");
                    aux = true;
                    break; 
                }
            }
            
            // Si el precio contiene una coma/punto, se parsea. Si no, se intenta parsear directamente.
            precio = Float.parseFloat(PrecioTXT);
            
            // 6. Asignar valores al Modelo
            NuePro.setNombre(txtNombre.getText().trim());
            NuePro.setPrecio(precio);
            NuePro.setSaborRelleno(sabor); 
            
            // 7. Llamar al método Guardar
            if(ctrl_nuepro.guardar(NuePro)) {
                JOptionPane.showMessageDialog(null, "Producto guardado con éxito.");
                // Limpiar campos después de guardar
                txtNombre.setText("");
                txtPrecio.setText("");
                jComboBox1.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el producto. Intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio debe ser un valor numérico válido (ej. 10 o 10.50).", "Advertencia", JOptionPane.WARNING_MESSAGE);
            System.err.println("Error de formato de número en precio: " + e.getMessage());
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado al guardar.", "Error", JOptionPane.ERROR_MESSAGE);
             System.err.println("Error al procesar los datos de nuevo producto: " + e.getMessage());
             e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    //METODO PARA CARGAR SABORES
    
   private void cargarComboSabores(){
        Connection cn = Conexion.conecta();
        
        // CORRECCIÓN CLAVE: Usamos DISTINCT para obtener solo los sabores únicos.
        String sql = "SELECT DISTINCT sabor_relleno FROM descripcion_producto ORDER BY sabor_relleno ASC";
        Statement st;
        
        try {
            
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Seleccione Sabor:" ); // Se agrega el item por defecto
            
            while(rs.next()){
                String sabor = rs.getString("sabor_relleno");
                // Aseguramos que los sabores se guarden con la primera letra en mayúscula por consistencia.
                if (sabor != null && !sabor.isEmpty()) {
                    String formattedSabor = sabor.substring(0, 1).toUpperCase() + sabor.substring(1).toLowerCase();
                    jComboBox1.addItem(formattedSabor);
                }
            }
            
            cn.close();
            
        } catch (SQLException e) {
            System.out.println("Error al cargar sabores: " + e.getMessage());
        }
        
    } 



}