
package Ventanas;
import java.sql.*;
import Conexion.Conexion;
import Controlador.ctrl_gestpro;
import Modelo.Producto;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author leona
 */
public class InternGestPro extends javax.swing.JInternalFrame {

    private int idproducto;
    public InternGestPro() {
        initComponents();
        this.setSize(800, 600);
        this.setTitle("Gestionar Productos");
        this.cargarTablaProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_GestPro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_GestPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_GestPro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 450));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestionar Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Actualizar.setBackground(new java.awt.Color(51, 255, 51));
        jButton_Actualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton_Eliminar.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Eliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 160, 130));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 210, 110));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        if(!txt_descripcion.getText().isEmpty()){
            Producto producto = new Producto();
            ctrl_gestpro controlgestpro = new ctrl_gestpro();
            producto.setNombre(txt_descripcion.getText().trim());
            
            if(controlgestpro.actualizar(producto, idproducto)){
                JOptionPane.showMessageDialog(null, "Producto Actualizado ");
                txt_descripcion.setText("");
                this.cargarTablaProducto();
            }else{
                JOptionPane.showMessageDialog(null, "Error al actualizar ");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un producto ");
        }
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
                if(!txt_descripcion.getText().isEmpty()){
            Producto producto = new Producto();
            ctrl_gestpro controlgestpro = new ctrl_gestpro();
            producto.setNombre(txt_descripcion.getText().trim());
            
            if(controlgestpro.eliminar( idproducto)){
                JOptionPane.showMessageDialog(null, "Producto Eliminado ");
                txt_descripcion.setText("");
                this.cargarTablaProducto();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar ");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un producto ");
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_GestPro;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables

    //Metodo para mostrar los productos
    
    private void cargarTablaProducto(){
        Connection con = Conexion.conecta();
        Connection cn = Conexion.conecta();
         if (con == null) {
            System.out.println("Error: no se pudo establecer la conexión a la base de datos");
            return;
        }
        
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select "
                + "nombre_producto.idproducto, "
                + "nombre_producto.nombre, "
                + "descripcion_producto.sabor_relleno, "
                + "descripcion_producto.costo, "
                + "descripcion_producto.precio, "
                + "inventario.cantidad "
                + "FROM nombre_producto INNER JOIN descripcion_producto on nombre_producto.idproducto = descripcion_producto.idproducto "
                + "INNER JOIN inventario on descripcion_producto.iddescp = inventario.iddescp; ";

        Statement st;
        
        try{
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InternGestPro.jTable_GestPro = new JTable(model);
            InternGestPro.jScrollPane1.setViewportView(InternGestPro.jTable_GestPro);
            
            model.addColumn("IdProducto");
            model.addColumn("Nombre");
            model.addColumn("Relleno");
            model.addColumn("Costo");
            model.addColumn("Precio");
            model.addColumn("Cantidad");
            
            while(rs.next()){
                Object fila[] = new Object[6];
                
                for (int i = 0; i < 6; i++){
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            
            con.close();
            
        }catch(SQLException e){
            System.out.println("Error al llenar la tabla Productos: " + e);
        }
        
        jTable_GestPro.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = jTable_GestPro.rowAtPoint(e.getPoint());
                int columna_point = 0;
                
                if(fila_point >= -1){
                    idproducto = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosProductoSeleccionado(idproducto);
                }
        }
        });
    }
    
    public void EnviarDatosProductoSeleccionado(int idproducto){
        try {
            Connection con = Conexion.conecta();
            PreparedStatement pst = con.prepareStatement(
                    "select * from nombre_producto where idproducto = '" + idproducto+"'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txt_descripcion.setText(rs.getString("nombre"));
            }
            
            con.close();
        } catch (Exception e) {
            System.out.println("Error al seleccionar categorias: " + e);
        }
        
    }
    
}
