/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Ventanas;
import Controlador.ctrl_nueusu;
import Modelo.Usuario;
import Utilidades.GeneradorUsuario;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author leona
 */
public class InternNueUsu extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternNueUsu
     */
    public InternNueUsu() {
        initComponents();
    }
    private void guardarNuevoUsuario() {
        ctrl_nueusu controlador = new ctrl_nueusu();
        Usuario nuevoUsuario = new Usuario();
        
        // Formato esperado para las fechas (YYYY-MM-DD)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        // 1. Recolección y validación de campos
        String nombre = txtNombre.getText().trim();
        String apPat = txtApPat.getText().trim();
        String apMat = txtApMat.getText().trim();
        String puesto = jComboBox1.getSelectedItem().toString().trim();
        String fecInStr = txtFecIn.getText().trim();
        String fecNacStr = txtFecNac.getText().trim();
        String telefono = txtTel.getText().trim();
        String password = txtPsw.getText().trim();
        
        if (nombre.isEmpty() || apPat.isEmpty() || apMat.isEmpty() || fecInStr.isEmpty() || 
            fecNacStr.isEmpty() || telefono.isEmpty() || password.isEmpty() || puesto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. Validación de fechas y conversión
        Date fecIngresoDate = null;
        Date fecNacimientoDate = null;
        
        try {
            fecIngresoDate = sdf.parse(fecInStr);
            fecNacimientoDate = sdf.parse(fecNacStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto. Use YYYY-MM-DD.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Validación de existencia (usando nombre completo)
        if (controlador.existeEmpleado(nombre, apPat, apMat)) {
            JOptionPane.showMessageDialog(null, "Ya existe un empleado con ese nombre y apellidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Generar el nombre de usuario de Login
        String usuarioLogin = GeneradorUsuario.generarUsuarioLogin(nombre, apPat, apMat, fecNacimientoDate);
        
        if (usuarioLogin == null) {
            JOptionPane.showMessageDialog(null, "Error interno al generar el nombre de usuario. Revise los datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 5. Asignar datos al modelo
        nuevoUsuario.setNombre(nombre);
        nuevoUsuario.setAppat(apPat);
        nuevoUsuario.setApmat(apMat);
        nuevoUsuario.setPuesto(puesto);
        nuevoUsuario.setFecingreso(fecIngresoDate);
        nuevoUsuario.setFecnac(fecNacimientoDate);
        nuevoUsuario.setTelefono(telefono);
        nuevoUsuario.setPassword(password);

        // 6. Guardar en la BD
        if (controlador.guardar(nuevoUsuario)) {
            
            // 7. Mostrar mensaje de éxito con el usuario generado
            String mensaje = "¡Usuario añadido correctamente!\n\n"
                            + "Nombre de Usuario (Login): " + usuarioLogin.toUpperCase() + "\n"
                            + "Contraseña: " + password;
            JOptionPane.showMessageDialog(null, mensaje, "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar campos
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar el empleado en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiarCampos(){
        txtNombre.setText("");
        txtApPat.setText("");
        txtApMat.setText("");
        jComboBox1.setSelectedIndex(0); // Reiniciar a la primera opción si es 'Vendedor'
        txtFecIn.setText("");
        txtFecNac.setText("");
        txtTel.setText("");
        txtPsw.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApPat = new javax.swing.JTextField();
        txtApMat = new javax.swing.JTextField();
        txtFecIn = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtPsw = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ap. Paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ap. Materno: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Puesto: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Ingreso: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 180, -1));
        getContentPane().add(txtApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, -1));

        txtApMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApMatActionPerformed(evt);
            }
        });
        getContentPane().add(txtApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, -1));

        txtFecIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecInActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 180, -1));
        getContentPane().add(txtFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 180, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 180, -1));

        txtPsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswActionPerformed(evt);
            }
        });
        getContentPane().add(txtPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 180, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Encargado", "Panadero" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApMatActionPerformed

    private void txtPswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswActionPerformed

    private void txtFecInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecInActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        this.guardarNuevoUsuario();
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtApMat;
    private javax.swing.JTextField txtApPat;
    private javax.swing.JTextField txtFecIn;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPsw;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
