/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Ventanas;
import Controlador.ctrl_produccion;
import Modelo.Produccion;
import Modelo.Produccion.ProductoCombinado; // <--- Importación clave
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.SpinnerNumberModel;
import javax.swing.JComboBox;
/**
 *
 * @author leona
 */
public class InternIngPro extends javax.swing.JInternalFrame {
    
    // Usaremos jComboBox1 para el relleno y jComboTipoPan para el nombre del producto
    private ProductoCombinado detalleSeleccionado = null; 
    
    /**
     * Creates new form InternIngProd
     */
    public InternIngPro() {
        initComponents();
        this.setTitle("Registro de Producción");
        this.setSize(650, 370);
        
        // Inicializar el modelo del JSpinner
        jSpinner1.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        
        // ** INICIALIZACIÓN DE JCOMBOBOX1 (RELLENO) **
        // Se inicializa el modelo del combo de relleno con el tipo ProductoCombinado.
        // Se asume que jComboBox1 está declarado como raw type (sin genérico) en initComponents.
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<ProductoCombinado>());
        jComboBox1.addItem(new ProductoCombinado("", "Seleccione Relleno", 0, ""));
        
        // Cargar solo los nombres de productos al combo principal
        cargarNombresProductos();
    }
    
    // Método que carga solo los nombres de producto en jComboTipoPan
    private void cargarNombresProductos() {
        ctrl_produccion controlador = new ctrl_produccion();
        List<String> nombres = controlador.obtenerNombresProductos();
        
        jComboTipoPan.removeAllItems();
        jComboTipoPan.addItem("Seleccione Producto");
        
        // Rellenar el combo de nombres de pan
        for (String nombre : nombres) {
            jComboTipoPan.addItem(nombre);
        }
    }
    
    // Método que carga los rellenos (jComboBox1) basados en el producto seleccionado (jComboTipoPan)
    private void cargarRellenosPorProducto(String nombreProducto) {
        // Aseguramos que el modelo sea limpio antes de añadir nuevos items
        jComboBox1.removeAllItems();
        // Usamos la clase ProductoCombinado para el item por defecto
        jComboBox1.addItem(new ProductoCombinado("", "Seleccione Relleno", 0, ""));
        detalleSeleccionado = null; // Resetear la selección
        
        if (!nombreProducto.equals("Seleccione Producto")) {
            ctrl_produccion controlador = new ctrl_produccion();
            // Obtenemos los detalles específicos del producto (incluyendo ID y Sabor)
            List<ProductoCombinado> detalles = controlador.obtenerDetallesPorNombre(nombreProducto);
            
            // Rellenar el combo de rellenos con los objetos ProductoCombinado
            for (ProductoCombinado pc : detalles) {
                jComboBox1.addItem(pc); 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboTipoPan = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonIngresar = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Pan:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo Relleno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jComboTipoPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoPanActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipoPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 210, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 210, -1));

        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 640, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
            // Lógica de Ingreso de Producción
        
        // 1. Obtener los valores seleccionados
        int cantidad = (Integer) jSpinner1.getValue();
        
        // Verificación doble del tipo ProductoCombinado
        if (detalleSeleccionado == null || detalleSeleccionado.getIdProducto() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un Producto y un Relleno válidos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validar cantidad
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad a producir debe ser mayor a cero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. Asignar datos al Modelo de Producción
        Produccion produccion = new Produccion();
        produccion.setIdproducto(detalleSeleccionado.getIdProducto());
        produccion.setIddescp(detalleSeleccionado.getIdDescp());
        produccion.setSaborRelleno(detalleSeleccionado.getSaborRelleno().trim());
        produccion.setCantidadProducida(cantidad);
        
        // 3. Llamar al Controlador
        ctrl_produccion controlador = new ctrl_produccion();
        if (controlador.registrarProduccion(produccion)) {
            String nombreCompleto = detalleSeleccionado.getNombreProducto() + " (" + detalleSeleccionado.getSaborRelleno() + ")";
            JOptionPane.showMessageDialog(null, "Producción de " + cantidad + " unidades de " + nombreCompleto.toUpperCase() + " registrada con éxito.\nEl inventario ha sido actualizado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar campos
            jComboTipoPan.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(0);
            jSpinner1.setValue(1);
        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar la producción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jComboTipoPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoPanActionPerformed
        // Obtenemos el producto seleccionado del combo de Nombres (es String)
        String productoSeleccionado = jComboTipoPan.getSelectedItem() != null ? jComboTipoPan.getSelectedItem().toString() : "Seleccione Producto";
        // Llamamos al método para recargar el combo de rellenos
        cargarRellenosPorProducto(productoSeleccionado);
    }//GEN-LAST:event_jComboTipoPanActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         Object item = jComboBox1.getSelectedItem();
        // Verificamos si el item es de la clase correcta antes de hacer el casting
        if (item instanceof ProductoCombinado) {
            detalleSeleccionado = (ProductoCombinado) item;
        } else {
            // Si es el ítem "Seleccione Relleno", detalleSeleccionado será null/vacío
            detalleSeleccionado = null; 
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jComboTipoPan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
